#服务配置
server:
  port: 9002
#spring配置
spring:
  #1.应用配置
  application:
    name: ihrm-system #指定服务名
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&amp;useSSL=false
    username: root
    password: root
  #3.JPA
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  redis:
    host: 127.0.0.1
    port: 6379
jwt:
    key: saas-ihrm
    ttl: 3600000 #有效值为1小时
ai:
  appId: 19436965
  apiKey: yZ3S1vTEZ0ctIHEU1p5xIgo6
  secretKey: OQC3VkQFqXrSZMczzmhEH34rarR2MWzy
  imageType: BASE64
  groupId: zhang
qr:
  url: http://localhost:8080/#/facelogin
